# Generated by Django 2.2.2 on 2019-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Speaker', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
            ],
        ),
    ]
