# Generated by Django 2.2.2 on 2019-06-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkApp', '0002_auto_20190603_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='Speaker',
            new_name='speaker',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='Venue',
            new_name='venue',
        ),
    ]
